const ProjectActionType = {
    ADD_PROJECT_START: 'ADD_PROJECT_START',
    ADD_PROJECT_SUCCESS: 'ADD_PROJECT_SUCCESS',
    ADD_PROJECT_ERROR: 'ADD_PROJECT_ERROR',
    GET_PROJECT_START: 'GET_PROJECT_START',
    GET_PROJECT_SUCCESS: 'GET_PROJECT_SUCCESS',
    GET_PROJECT_ERROR: 'GET_PROJECT_ERROR',
    DELETE_PROJECT_START: 'DELETE_PROJECT_START',
    DELETE_PROJECT_SUCCESS: 'DELETE_PROJECT_SUCCESS',
    DELETE_PROJECT_ERROR: 'DELETE_PROJECT_ERROR'
}

export default ProjectActionType;