const TaskActionType = {
    GET_BACKLOG_START: "GET_BACKLOG_START",
    GET_BACKLOG_SUCCESS: "GET_BACKLOG_SUCCESS",
    GET_BACKLOG_ERROR: "GET_BACKLOG_ERROR",
    GET_TASK_START: "GET_TASK_START",
    GET_TASK_SUCCESS: "GET_TASK_SUCCESS",
    GET_TASK_ERROR: "GET_TASK_ERROR",
    DELETE_TASK_START: "DELETE_TASK_START",
    DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
    DELETE_TASK_ERROR: "DELETE_TASK_ERROR",
    ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
    ADD_TASK_START: "ADD_TASK_START",
    ADD_TASK_ERROR: "ADD_TASK_ERROR",
    UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
    UPDATE_TASK_ERROR: "UPDATE_TASK_ERROR",
    UPDATE_TASK_START: "UPDATE_TASK_START"
}

export default TaskActionType;